# Generated by Django 4.0.6 on 2022-07-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_auto_20220712_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cc',
            name='banco',
            field=models.CharField(blank=True, choices=[('BP', 'BANRISUL PASQUALOTO'), ('BRP', 'BANRISUL RP'), ('SP', 'SICREDI')], max_length=4, null=True),
        ),
    ]
